import { RoulettePrize } from './types'

export const INITIAL_ROULETTE_PRIZES: RoulettePrize[] = [
  {
    id: 'prz-dragon',
    name: 'Dragon Fruit (Rework)',
    description: 'A fruta mítica mais cobiçada e poderosa do Blox Fruits! Dano massivo e transformação dracônica.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/a/a2/DragonFruit.png/revision/latest?cb=20230221081530',
    rarity: 'mythic',
    probability: 1.0,
    redemption_type: 'discord',
    delivery_info: 'Entrega manual via trade em servidor VIP com suporte prioritário.',
    is_active: true,
    display_order: 1,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-kitsune',
    name: 'Kitsune Fruit (Física)',
    description: 'Fruta mítica de 9 caudas com chamas azuis, hipervelocidade e combos devastadores.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/7/7b/KitsuneFruit.png/revision/latest?cb=20231225091720',
    rarity: 'mythic',
    probability: 2.0,
    redemption_type: 'discord',
    delivery_info: 'Entrega manual em servidor VIP ou trade com a equipe Ashens.',
    is_active: true,
    display_order: 2,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-conta-godhuman',
    name: 'Conta Max 2550 + Godhuman',
    description: 'Conta no nível máximo com estilo Godhuman desbloqueado e itens avançados.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/0/05/Godhuman.png/revision/latest?cb=20220912195033',
    rarity: 'legendary',
    probability: 2.0,
    redemption_type: 'discord',
    delivery_info: 'Envio de login e dados da conta via ticket seguro no Discord.',
    is_active: true,
    display_order: 3,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-dark-blade',
    name: 'Dark Blade / Yoru (Gamepass)',
    description: 'A espada lendária de Dracule Mihawk! Lâmina negra com cortes de energia verde.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/a/a7/DarkBlade.png/revision/latest?cb=20200806085532',
    rarity: 'legendary',
    probability: 3.0,
    redemption_type: 'discord',
    delivery_info: 'Envio via presente de Gamepass no Roblox ou servidor VIP.',
    is_active: true,
    display_order: 4,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-leopard',
    name: 'Leopard Fruit (Física Mítica)',
    description: 'Fruta Besta lendária com velocidade absurda e ataques furiosos ininterruptos.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/9/91/LeopardFruit.png/revision/latest?cb=20220910214619',
    rarity: 'legendary',
    probability: 4.0,
    redemption_type: 'discord',
    delivery_info: 'Entrega via trade em servidor VIP oficial.',
    is_active: true,
    display_order: 5,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-trex',
    name: 'T-Rex Fruit (Mítica)',
    description: 'Fruta pré-histórica mítica com rugido atordoante e alto dano corpo a corpo.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/8/87/TRexFruit.png/revision/latest?cb=20231225091745',
    rarity: 'epic',
    probability: 5.0,
    redemption_type: 'automatic',
    delivery_info: 'Entrega automática no inventário ou código de resgate.',
    is_active: true,
    display_order: 6,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-dough',
    name: 'Dough / Massa Fruit',
    description: 'A rainha incontestável do PVP! Stun infinito e dano explosivo em área.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/4/41/DoughFruit.png/revision/latest?cb=20220910214845',
    rarity: 'epic',
    probability: 7.0,
    redemption_type: 'automatic',
    delivery_info: 'Entrega automática instantânea.',
    is_active: true,
    display_order: 7,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-2x-mastery',
    name: 'Gamepass 2x Maestria',
    description: 'Duplica toda a maestria obtida em espadas, frutas e estilos de luta.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/0/05/2xMastery.png/revision/latest?cb=20210214214643',
    rarity: 'epic',
    probability: 8.0,
    redemption_type: 'automatic',
    delivery_info: 'Gift direto para o nick informado no Roblox.',
    is_active: true,
    display_order: 8,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-2x-money',
    name: 'Gamepass 2x Dinheiro',
    description: 'Dobre todos os Belis obtidos derrotando NPCs e chefes no jogo.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/4/48/2xMoney.png/revision/latest?cb=20210214214620',
    rarity: 'rare',
    probability: 8.0,
    redemption_type: 'automatic',
    delivery_info: 'Gift direto para o nick informado no Roblox.',
    is_active: true,
    display_order: 9,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-buddha',
    name: 'Buddha Fruit (Física)',
    description: 'A fruta perfeita para upar nível e maestria em velocidade recorde.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/8/80/BuddhaFruit.png/revision/latest?cb=20211107221350',
    rarity: 'rare',
    probability: 15.0,
    redemption_type: 'automatic',
    delivery_info: 'Entrega automática.',
    is_active: true,
    display_order: 10,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-lendaria-aleatoria',
    name: 'Fruta Lendária Aleatória',
    description: 'Sorteio de uma fruta lendária como Portal, Blizzard, Som ou Rumble.',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/8/89/PortalFruit.png/revision/latest?cb=20221217032729',
    rarity: 'rare',
    probability: 20.0,
    redemption_type: 'automatic',
    delivery_info: 'Sorteada e entregue no chat do resgate.',
    is_active: true,
    display_order: 11,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'prz-bonus-beli',
    name: 'Bônus 500.000 Beli + Fruta Rara',
    description: 'Pacote de recursos com 500k de moedas Beli e uma fruta rara de suporte (Magma / Light).',
    image_url: 'https://static.wikia.nocookie.net/roblox-blox-piece/images/a/ab/LightFruit.png/revision/latest?cb=20211107221415',
    rarity: 'common',
    probability: 25.0,
    redemption_type: 'automatic',
    delivery_info: 'Instruções de resgate entregues no ato.',
    is_active: true,
    display_order: 12,
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
]
